name: CI
permissions:
  contents: read
on:
  push:
  pull_request:

jobs:
  check:
    name: Lint, Format, Typecheck and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          submodules: true

      - name: Setup RoKit
        uses: CompeyDev/setup-rokit@1d9390883f7ebce19d48f5b8d006e11d387c92ab

      - name: Install RoKit packages
        run: make install

      - name: Required checks
        run: make ci
